# Generated by Django 4.0 on 2022-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_song_song_song_language_song_song_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Neutral', 'Neutral')], default='Happy', max_length=20),
        ),
    ]
