# Generated by Django 4.0 on 2022-03-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_song_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Neutral', 'Neutral'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
