# Generated by Django 4.0 on 2022-03-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_song_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mood',
            field=models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Fear', 'Fear'), ('Angry', 'Angry'), ('Neutral', 'Neutral'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
