# Generated by Django 4.1.7 on 2026-08-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_alter_song_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
