# Generated by Django 4.1.7 on 2026-08-23 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Approved', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
