# Generated by Django 4.1.7 on 2026-08-23 21:43

from django.db import migrations


def backfill_groups(apps, schema_editor):
    Playlist = apps.get_model('musicapp', 'Playlist')
    PlaylistGroup = apps.get_model('musicapp', 'PlaylistGroup')

    pairs = Playlist.objects.filter(group__isnull=True).values_list(
        'user_id', 'playlist_name').distinct()
    for user_id, playlist_name in pairs:
        group = PlaylistGroup.objects.create(name=playlist_name, owner_id=user_id)
        Playlist.objects.filter(
            user_id=user_id, playlist_name=playlist_name, group__isnull=True
        ).update(group=group)


def reverse_backfill(apps, schema_editor):
    PlaylistGroup = apps.get_model('musicapp', 'PlaylistGroup')
    PlaylistGroup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_playlistgroup_playlist_group'),
    ]

    operations = [
        migrations.RunPython(backfill_groups, reverse_backfill),
    ]
