# Generated by Django 4.1.7 on 2026-08-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_backfill_playlist_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodlog',
            name='source',
            field=models.CharField(choices=[('camera', 'Camera'), ('text', 'Text')], default='camera', max_length=10),
        ),
    ]
