# Generated by Django 4.1.7 on 2026-08-24 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0014_spotifyaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('album', models.CharField(blank=True, max_length=500)),
                ('image', models.URLField(blank=True, max_length=1000)),
                ('external_url', models.URLField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='spotify_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.spotifytrack'),
        ),
    ]
